#!/bin/bash

# GDR [0] - Screen
tmux new -s GDR -d
tmux rename-window -t GDR explorer
tmux send-keys -t GDR 'screenfetch -c 6,3' C-m
# GDR [1] - Entrain
tmux new-window -t GDR
tmux rename-window -t GDR entrain
tmux send-keys -t GDR 'cd ~/research/projects/nuclear-hydrodynamics-fork/GDR/' C-m
tmux split-window -h -t GDR
tmux send-keys -t GDR 'cd ~/research/projects/nuclear-hydrodynamics-fork/GDR/' C-m
# GDR [2] - journal
tmux new-window -t GDR
tmux rename-window -t GDR journal
tmux send-keys -t GDR 'cd ~/research/projects/nuclear-hydrodynamics-fork/GDR/' C-m
tmux send-keys -t GDR 'vim ryan-journal.txt' C-m

# Writing Screen
tmux new -s writing -d
tmux rename-window writing base
# mccarthy project
tmux new-window -t writing
tmux rename-window -t writing mccarthy
tmux send-keys -t writing 'cd ~/Dropbox/Writing/Cormac\ McCarthy/Cormac\ McCarthy\ Annotated/_data/' C-m

# Jupyter Server
tmux new -s Jupyter -d
tmux rename-window Jupyter server
tmux send-keys -t Jupyter 'j' C-m

# Final Attach
tmux select-window -t GDR:0
tmux attach -t GDR
